### ISSUE TITLE
After updgrading to 1.0.9 custom HttpHandler only receives .mvt url in onRequest

### ISSUE THREAD

**Issue by yanickv** [mapzen/android#160] opened 2016-08-15 01:24 UTC
Hi,

I upgraded from 1.0.6 to 1.0.9 and since then my cutom HttpHandler only receives .mvt url requests. It seems to ignore the source.osm.url that is specified in my .yaml.

    sources:
        osm:
            # EraserMaps the app only supports MVT format tiles
            type: TopoJSON #GeoJSON, MVT, TopoJSON
            url:  https://vector.mapzen.com/osm/all/{z}/{x}/{y}.topojson?api_key=vector-tiles-xxxxxxxxxxxxx

I tried to set the url by code but it does not work either:

    controller.queueSceneUpdate("sources.osm.url", "https://localhost/osm/all/{z}/{x}/{y}.topojson");
    controller.queueSceneUpdate("sources.osm.url_params", "{ api_key: ${MY_API_KEY} }");
    controller.applySceneUpdates();

Another issue I observed is that passing the style in getMapAsync does not work anymore. I had to replace this by a call to setStyle().

     mapFragment.getMapAsync(new MYStyle(), new OnMapReadyCallback() { // doesnt work...

**Comment by blair1618** [comment] 2016-08-15 17:11
There is probably an issue here in tangram-es. From a brief look at the code, it looks like we may not be correctly updating data sources in certain cases - I'll investigate and create an issue on [tangram-es](https://github.com/tangrams/tangram-es). I'm less clear about the issue with getMapAsync though - @sarahlensing do you have any ideas on the style setting problem?

**Comment by sarahlensing** [comment] 2016-08-15 19:57
It looks like we introduced a bug when we added support for persisting the map state that prevented the style from being explicitly set. I've created a PR (https://github.com/mapzen/android/pull/161) which resolves the issue. Thanks for the report @yanickv

**Comment by ecgreb** [comment] 2016-08-15 20:03
Style setting issue should now be resolved in the latest snapshot build but let's keep this issue open until the problem is resolved with `HttpHandler` not invoked for alternate tile formats.

@blair1618 can you link to the issue in the Tangram ES project once it is created?

**Comment by blair1618** [comment] 2016-08-15 21:03
https://github.com/tangrams/tangram-es/issues/912

**Comment by ecgreb** [comment] 2016-08-19 19:27
https://github.com/mapzen/android/issues/162

**Comment by ecgreb** [comment] 2016-09-08 21:06
`HttpHandler` fix should now be available in the latest `1.0.10-SNAPSHOT` build.

**Closed by ecgreb** 2016-09-08 21:06 UTC
Labels: bug, in progress

**Comment by yanickv** [comment] 2016-09-09 14:42
Thanks a lot for the fix. I will try out the new 1.0.10 when it is available. In the meantime I had changed the source name.
